import type { Metadata } from "../../frontend/node_modules/next";
import "../globals.css";
import ClientLayout from "@/components/layout/client-layout";

export const metadata: Metadata = {
  title: "Seek",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ClientLayout>{children}</ClientLayout>;
}
